[2023-06-18T06:04:23.155+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-06-18T06:04:23.171+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.Print_time scheduled__2023-06-18T05:00:00+00:00 [queued]>
[2023-06-18T06:04:23.183+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.Print_time scheduled__2023-06-18T05:00:00+00:00 [queued]>
[2023-06-18T06:04:23.183+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-18T06:04:23.201+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): Print_time> on 2023-06-18 05:00:00+00:00
[2023-06-18T06:04:23.208+0000] {standard_task_runner.py:57} INFO - Started process 295 to run task
[2023-06-18T06:04:23.215+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'Print_time', 'scheduled__2023-06-18T05:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp8_59cwf2']
[2023-06-18T06:04:23.218+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask Print_time
[2023-06-18T06:04:23.243+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-06-18T06:04:23.304+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.Print_time scheduled__2023-06-18T05:00:00+00:00 [running]> on host 604c1bbb6229
[2023-06-18T06:04:23.322+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-06-18T06:04:23.452+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='Print_time' AIRFLOW_CTX_EXECUTION_DATE='2023-06-18T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-18T05:00:00+00:00'
[2023-06-18T06:04:23.454+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 11, in get_time
    date = date.now()
UnboundLocalError: local variable 'date' referenced before assignment
[2023-06-18T06:04:23.469+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=first_dag, task_id=Print_time, execution_date=20230618T050000, start_date=20230618T060423, end_date=20230618T060423
[2023-06-18T06:04:23.486+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 6 for task Print_time (local variable 'date' referenced before assignment; 295)
[2023-06-18T06:04:23.508+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-18T06:04:23.535+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
